# Generated by Django 5.1 on 2024-08-30 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha', models.DateField(verbose_name='Fecha Vencimiento')),
                ('pagado', models.BooleanField(default=False)),
                ('plantilla', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Registros.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Renglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('dia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('activo', models.BooleanField(default=True)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registros.plantilla')),
            ],
        ),
    ]
